id: P010523
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W29235
  title: རིག་གནས་སྙིང་སྟོབས
  author: ''
  volumes:
    f018feea1eba4b4b96cd78358da2768d:
      image_group_id: I5256
      title: ''
      volume_number: 1
      total_pages: 312
      base_file: v001.txt
