id: I90945512
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T05:55:49+00:00'
last_modified: '2022-06-08T14:14:02.115451+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29235
  title: རིག་གནས་སྙིང་སྟོབས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    F4B9:
      image_group_id: I5256
      title: ''
      total_pages: 312
      order: 1
      base_file: F4B9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
